### PR TITLE
eiskaltdcpp-2.4.1 (untested)

### PR DESCRIPTION
**Pull request by tehnick**
[ChangeLog](https://github.com/eiskaltdcpp/eiskaltdcpp/blob/v2.4.1/ChangeLog.txt)

GTK+ UI will be removed soon, see: [TODO list](https://github.com/eiskaltdcpp/eiskaltdcpp/blob/v2.4.1/TODO) and [plans to next major release](https://github.com/eiskaltdcpp/eiskaltdcpp/milestone/3)

### CODE REVIEW

**Comment by tehnick** [comment]
Some parts of patch already accepted in upstream:
https://github.com/eiskaltdcpp/eiskaltdcpp/commit/ffd6718b5fd815282fc3affc7c08f86c7f596f39
https://github.com/eiskaltdcpp/eiskaltdcpp/commit/fc9bc0c2c281a6b186af014591204483169e0cfd

**Comment by fd00** [comment]
@tehnick 
Thanks for the pull request. 😄 

I tried to build it using *.cygport and *.src.patch, but I got an error.

```
CMake Error at /usr/share/cmake-3.17.3/Modules/FindPackageHandleStandardArgs.cmake:164 (message):
  Could NOT find Miniupnpc (missing: MINIUPNP_LIBRARY MINIUPNP_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.17.3/Modules/FindPackageHandleStandardArgs.cmake:445 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindMiniupnpc.cmake:6 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:125 (find_package)
```
```
CMake Error at eiskaltdcpp-qt/CMakeLists.txt:21 (find_package):
  By not providing "FindQt5Multimedia.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "Qt5Multimedia", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5Multimedia"
  (requested version 5.0.2) with any of the following names:

    Qt5MultimediaConfig.cmake
    qt5multimedia-config.cmake

  Add the installation prefix of "Qt5Multimedia" to CMAKE_PREFIX_PATH or set
  "Qt5Multimedia_DIR" to a directory containing one of the above files.  If
  "Qt5Multimedia" provides a separate development package or SDK, be sure it
  has been installed.
```

Do you install miniupnpc and libQt5Multimedia in your cygwin environment?

**Comment by tehnick** [comment]
@fd00 I updated README. Could you check is everything fine now?

**Comment by fd00** [comment]
@tehnick 
`cygport package` failed.

```
$ cygport eiskaltdcpp-2.4.1-1bl1.cygport package
(snip)
>>> Checking packages for unexpected, missing or duplicate files
*** Warning: Packages are missing files:
-usr/bin/cygeiskaltdcpp-2.4.dll
*** ERROR: Packages are missing files:
$
```

Please fix `PKG_NAMES`

```
diff --git a/eiskaltdcpp/eiskaltdcpp-2.4.1-1bl1.cygport b/eiskaltdcpp/eiskaltdcpp-2.4.1-1bl1.cygport
index cfd8170b..5d4b5381 100644
--- a/eiskaltdcpp/eiskaltdcpp-2.4.1-1bl1.cygport
+++ b/eiskaltdcpp/eiskaltdcpp-2.4.1-1bl1.cygport
@@ -31,7 +31,7 @@ CYGCMAKE_ARGS="
 
 PKG_NAMES="
 	${PN}
-	lib${PN}${PV}
+	lib${PN}2.4
 	lib${PN}-devel
 "
 eiskaltdcpp_CONTENTS="

```

All committed READMEs are generated automatically by [xezat](https://github.com/fd00/xezat).

After merging the README of this pull request, I think I will overwrite it with the regenerated README, is that ok?

**Comment by tehnick** [comment]
> I think I will overwrite it with the regenerated README, is that ok?

Yes, sure. Thanks!

**Comment by tehnick** [comment]
BTW, I do not believe that Cygwin users really need a separate library `libeiskaltdcpp` and development files for it. How about removing them? If you agree with their removal, just use these `cmake` options:
```
    -DWITH_DEV_FILES:BOOL=OFF
    -DLINK=STATIC
```

**Comment by fd00** [comment]
It seems to be common for official Cygwin packages to provide development files and runtime, so yacp follows that policy.

* https://cygwin.com/packages/package_list.html#l

I think that developers who only need executables can build their own packages.

**Comment by tehnick** [comment]
I see.

**Comment by fd00** [comment]
Sorry for the delay. We will take care of the rest of the corrections here.

**Comment by tehnick** [comment]
Thanks!

**Pull request merged**
